spring:
  application:
    name: smart-ai-service

  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/smart_customer_service?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Redis配置
  data:
    redis:
      host: 192.168.101.68
      port: 6379
      password: redis
      database: 0

  # WebSocket配置
  websocket:
    memory-broker-session-expiry: 1800000

  # LangChain4j配置
langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${API_KEY}
      model-name: qwen-plus

  session:
    store-type: redis
    redis:
      namespace: smart-ai-service

server:
  port: 8081

# Nacos配置
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
        username: nacos
        password: nacos

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,ai-service
  endpoint:
    health:
      show-details: always

# 日志配置
logging:
  level:
    org.example.smart.ai: DEBUG
    dev.langchain4j: DEBUG