spring:
  application:
    name: smart-ai-service

  jackson:
    serialization:
      indent-output: true

  # R2DBC 数据源配置
  r2dbc:
    url: r2dbc:mysql://localhost:3306/smart_customer_service?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 1234
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m

  # Redis配置
  data:
    redis:
      host: 192.168.101.68
      port: 6379
      password: redis
      database: 0

  # Elasticsearch配置
  elasticsearch:
    uris: https://10.105.6.89:9201/
    username: elastic
    password: Cr=1TwP4deZNBHrfKPwY
    connection-timeout: 10s
    socket-timeout: 30s

  # Nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
        username: nacos
        password: nacos

server:
  port: 8081

# LangChain4j配置
langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${API_KEY}
      model-name: qwen-plus
    streaming-chat-model: #流式模型配置
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${API_KEY}
      model-name: qwen-plus
      log-requests: true
      log-responses: true

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,ai-service
  endpoint:
    health:
      show-details: always

# 日志配置
logging:
  level:
    org.example.smart.ai: DEBUG
    dev.langchain4j: DEBUG

# SpringDoc OpenAPI 配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs